services:
  - type: web
    name: belo-frango-pdv
    env: node
    plan: free
    buildCommand: rm -rf node_modules && npm install --build-from-source
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
